### ISSUE TITLE
Present our technical strengths and team management philosophy

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#15]

**Comment by xllRyan** [comment]
hello, im ryan. i have some prior knowledge of markup language to create websites. i bellieved in a team that not only does the team leader can voice out their opinions but also its  members.

**Comment by Sy989** [comment]
Hello, I am Sze Ying. My technical strengths are UX design like photoshop/video editing. I also have some knowledge about some programming languages. I believe being democratic is the best way for a team to work together

**Comment by Elsonnnn** [comment]
Hello, i’m Elson. My technical skills include programming in languages such as Python and C, as for team philosophy, I believe that decisions should not only be made by the team leader, but also everyone involved in the project.

**Comment by 2101035** [comment]
Hi everyone, I am Lay Kiat. Nice to meet you all.
I have knowledge in some programming languages such as C, C++, python and java.
I believe that in a team, the feedback from all members are important to allow for growth.
