### ISSUE TITLE
Weekly Meeting to update on the Project  Progress

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#18]
Meetup Dates:
Past:
31 August 2022
2 September 2022
9 September 2022
16 September 2022 
Upcoming:
23 September 2022

**Comment by xllRyan** [comment]
pls take note of the upcming date

**Comment by 2101035** [comment]
Update for 24 Nov 2022



![Image](https://user-images.githubusercontent.com/94104852/203723914-79275998-6178-40ce-9a05-88b05b32cabc.jpg)



![Image](https://user-images.githubusercontent.com/94104852/203723931-6fe75649-0646-454a-a886-dad2a0507c77.jpg)



![Image](https://user-images.githubusercontent.com/94104852/203723952-5f1cff63-61d9-4bc4-ac82-b4f4acb865a4.jpg)
