### ISSUE TITLE
1.4.1 Use case diagram( Actor: Staff and IT )

### ISSUE THREAD

**Issue by 2101035** [2101035/ICT2201-Team-Project-p1-7#20]
The purpose of a use case diagram in UML is to demonstrate the different ways that a user might interact with a system. The usecase split up will be between different roles.

**Comment by xllRyan** [comment]
https://lucid.app/lucidchart/a1211635-5baf-4407-b0aa-eab239686af7/edit?viewport_loc=453%2C183%2C1030%2C1196%2C0_0&invitationId=inv_65363656-4a60-4775-9ac6-e468ad5ef668#
