### ISSUE TITLE
Doing Milestone 1 Report

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#23]
M1: assessed on the Software Requirements Specification and project planning.
Assessment rubrics:
o Requirements Specifications (20%)
o Use Case diagram and descriptions (20%)
o Project Planning & Estimation (11%)
o Team Management (8%)
o Report format and writing (6%)
o (Individual) Task management and competence (20%)
o (Individual) Task reflections for M1 (15%)
o Bonus Marks^: >=95% of the requirements covered realistic for the project plan and
development time (3%), the use case diagram covers all requirements gathered, and
all use cases are accompanied by a well-written use case description (7%).

**Comment by Elsonnnn** [comment]
Left the wireframe + description

**Comment by 2101035** [comment]
Report and complementary documents submitted to school LMS in pdf format.
