### ISSUE TITLE
1.3 background literature

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#24]
A better understand of what is our project all about and what are some reference we can find online. Do take the time to research

**Comment by Elsonnnn** [comment]
Sonal Gupta and Anshika Mittal from the University of Delhi published the work. These thesis papers discussed how crucial work-life balance is. If not treated seriously, it could develop into a problem. However, with effort and vigilance, it can be a success as well.  Highlighted that adaptability in an organisation is the key to unlocking the door of opportunities and success. While work is vital, other aspects of life, including family and health, cannot be overlooked.[1]


The ambulance care assistant and patient transport service (PTS) drivers will drive the disabled, elderly, sick, or vulnerable people to and from outpatient clinics, daycare centers, and routine hospital admissions.
Emergency care assistants are part of emergency ambulance crews attending 999 calls.
Paramedics will often be one of the first to arrive when a patient needs help. It is a fast-paced and vital role where you will need to take charge of the situation to save lives quickly.
