### ISSUE TITLE
2.2.0 [ remove ] wireframe

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#25]
A wireframe is a layout of a web page that demonstrates what interface elements will exist on key pages

**Comment by xllRyan** [comment]
lets work on the wireframe

**Comment by 2101035** [comment]
Let's split this task into 4 taskings:
wireframe 1: login page and changing of credentials (assigned: Ryan)
wireframe 2: IT admin pages (assigned: Sze Ying)
wireframe 3: Manager pages (assigned: Lay Kiat)
wireframe 4: Staff pages (assigned: Elson)

**Comment by Sy989** [comment]
done

**Comment by xllRyan** [comment]
done for wireframe 1

**Comment by Elsonnnn** [comment]
done

**Comment by 2101035** [comment]
Wire frame 3 done
