### ISSUE TITLE
2.2.1 [ Remove ] Wireframe 1(login page and changing of credentials)

### ISSUE THREAD

**Issue by Sy989** [2101035/ICT2201-Team-Project-p1-7#26]

**Comment by xllRyan** [comment]
Login page
![Image](https://user-images.githubusercontent.com/20891220/191905426-a71b6796-7863-4b2a-b2c3-1758c3082ce5.png)

Change password for manager


![Image](https://user-images.githubusercontent.com/20891220/191905614-2c4bcfd5-9973-44b1-817a-27bfd2c5df8b.png)



![Image](https://user-images.githubusercontent.com/20891220/191905642-e72d33bc-bf88-4275-9a30-e7c782fc1309.png)


Change password for Staff


![Image](https://user-images.githubusercontent.com/20891220/191905689-c2d33454-7be7-4488-b0ca-08703dc276f5.png)



![Image](https://user-images.githubusercontent.com/20891220/191905723-e055afc1-571f-4b59-a679-d8da7cab7616.png)

**Comment by xllRyan** [comment]
Done for wireframe
