### ISSUE TITLE
2.2.3 [ Remove ]Wireframe 3(Manager pages)

### ISSUE THREAD

**Issue by Sy989** [2101035/ICT2201-Team-Project-p1-7#28]

**Comment by 2101035** [comment]
Doing the wire frame using balsamiq

**Comment by 2101035** [comment]
Landing page for manager

![Image](https://user-images.githubusercontent.com/94104852/191905424-034fc265-b383-42f5-8172-c0513112a90c.png)


![Image](https://user-images.githubusercontent.com/94104852/191905535-caec4eaf-d9cd-494e-b058-042c507437bf.png)

**Comment by 2101035** [comment]
Manager Job Allocation


![Image](https://user-images.githubusercontent.com/94104852/191905802-72f9da4e-af0e-4273-91aa-26b923ef79f9.png)
