### ISSUE TITLE
2.2.4 [ Removed ]Wireframe 4 (Staff Pages)

### ISSUE THREAD

**Issue by Sy989** [2101035/ICT2201-Team-Project-p1-7#29]

**Comment by Elsonnnn** [comment]
Wireframe for the staff pages (staff landing page, staff job availability page)


![Image](https://user-images.githubusercontent.com/90232363/191905199-0e49a738-abd8-4f1e-b7a1-2ae0c3ffbfc2.png)



![Image](https://user-images.githubusercontent.com/90232363/191905220-2dd8f2e4-13c4-455b-82c9-a966fd47a5ce.png)
