### ISSUE TITLE
1.2.1 functional requirements

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#4]
FR1: The system shall allow staff to see their weekly job assignments, 
FR2: The system shall generate a job workload display on the landing page for the staff.
FR3: The system shall allow staff to add their unavailability up to 5 weeks ahead of time
FR4: The system shall allow staff to edit their availability up to 5 weeks ahead of time
FR5: The staff can reject job assigned by manager
FR6: The staff is able to indicate their job allocation for the week
FR7: Manager can view staff workload(number of hours they have to work) on the manager landing page
FR8: Manager can view up to 3 staffs availability according to the top 3 lowest workload on the manager landing page
FR9: Manager views staff with over 40 hours of workload for the week on the manager landing page
FR10: Manager assigns staff for job allocation for 1 week at a time
FR11: Manager can view the staff’s assigned workload on the landing page
FR12: Manager can view staff job preference for the week
FR13: Manager can view the staff’s location at a particular date
FR14:The IT Administrator will add new staff into the system.
FR15: The IT Administrator will add new managers into the system
FR16: Manager and staff will change their password after every 90 days

**Comment by 2101035** [comment]
Functional requirements updated
