### ISSUE TITLE
M1 Deliverable Updates: What is your project about?

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#47]
A Workload management system on the web for ambulance services which will provide an interactive and visual way for the employee to see their overall workload for the month. The system allows the employee to add and edit their availability for up to 5 weeks ahead of time. Employees are able to reject jobs assigned to them, however, they would need to discuss offline with their manager before proceeding with the rejection.
The manager will be able to view all the employee workloads assigned, Display weekly job availability, and allocate the job to an employee who is available. Managers will be able to view the employee's location on a particular date.
Manager will be able to view the top 3 employees with the lowest workload and highlight employees that has over 40 hours of job allocated.
IT Administrator will create the Manager and Employee accounts before the user is able to log in to their own personal account.

**Comment by xllRyan** [comment]
will updates by 10/10/2022

**Comment by xllRyan** [comment]
do look through and see if there is any issue with it

**Comment by 2101035** [comment]
Looks okay, let's use this for our M2 report.
