### ISSUE TITLE
M1 Deliverable updates: Requirement Elicitation Method for Project Overview

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#49]
For our workload management for ambulance services, we have use documentation and interview technique. 
For the documentation, we have looked through what is the project requirement from the clients and think through what would be the better choices to deal with the problems. 
For the interview technique, we arranged a time with the client to have a client meeting. To further discuss on the project requirement that are not clear to us. Prior to the client meeting, we have come up with client meeting questions that we intend to ask the client.

**Comment by xllRyan** [comment]
will make the changes and update on 8 Oct 2022.

**Comment by Elsonnnn** [comment]
okay that's good
