### ISSUE TITLE
M1 Deliverable updates: Data Dictionary

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#56]

**Comment by Sy989** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-922f440e-7fff-06a9-7112-8a2ffd60864b"><div dir="ltr" style="margin-left:0pt;" align="left">

Administrative Staff | Can be referred to as managers with privileges to assign employees jobs.
-- | --
IT Administrator | Create accounts for staff and administrative staff.
Employee | Drivers, care assistants, and paramedics are considered as staff. Staff is referred to as people working in the ambulance team of the hospital.
Manager | Can be referred to as administrative staff
Staff | Can be referred to as employee
Web application | An application program that is stored on a remote server and delivered over the Internet through a browser interface.
Interactive | Allowing a two-way flow of information between a computer and a computer-user; responding to a user’s input.
Job Peference | An employee’s availability to work on specific days.
UI | UI refers to User Interface
ECB | ECB stands for Entity-Control-Boundary
Elicitation | The process of getting or producing something, especially information or a reaction
OD | OD refers to Optimistic Duration
PD | PD refers to Pessimistic duration
ED | ED refers to Expected duration
Optimistic Duration | Estimation of the minimum amount of time it would take to perform the task
Pessimistic duration | Estimation of the maximum amount of time it would take to perform the task
Expected duration | Estimation of the expected duration that will be needed to perform the task
Project Estimation | Weighted average of the most likely duration
Weighted average of the most likely duration | D=((1XOD) + (4XED) + (1XPD))/6
Web | Web refers to website

</div><br /></b>
</body>
</html>

**Comment by Elsonnnn** [comment]
okay great job
