### ISSUE TITLE
2.3 M2 Introduction Product Scope

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#58]

**Comment by Elsonnnn** [comment]
INTRO
Our team has been tasked by our clients with developing a workload management system on the web, to provide a way for both employees and management to view their current workload as well as assign jobs equally among employees. The workload management system will be a way for the hospital staff to have a healthy work-life balance and for managers to promote a healthy working culture among staff.

PRODUCT SCOPE
This product is a web application workload management system that would be an informative way to provide an overview of the company’s manpower strength at any time. The system should also provide a way for management to assign shifts based on the availability indicated by each employee, as well as for employees to accept or reject assigned jobs.

With this system, we hope that the workload will be evenly distributed among the employees at the major hospital, to make the workplace environment more attractive for the employees by promoting a healthy work-life balance for employees.

This project will be taken on for 12 weeks, with updates in the form of reports that will be submitted at three predefined milestones. (Including this one)
