### ISSUE TITLE
2.4 M2 Intended Audience and Document Overview

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#59]

**Comment by Sy989** [comment]
This document is intended for the client as well as the university professors. This document will also serve as a guideline for the project's developers. 

This document will cover the designs such as the software ECB diagrams, component diagrams, sequence diagrams, and software architecture patterns as well as the software design patterns.

The documents will be broken into 5 important sections.
Overall Section
This section will cover a summary of our entire project, from the initial phase to the current state requirement in the M2 Report.

Specific Requirement
This section will cover the new requirement and changes from the M1 Report. Any requirement that is removed will also be listed down here. 

Software design
This section will cover our software architecture design followed by the different types of diagrams such as class, sequence, and components diagrams.

Project Planning
This section will cover the resources required for the project and if there are any overruns for the project.

Individual member task distribution
This section will cover the reflection of each member on what they have done, what they have learned, and how to better improve if they were to be given another chance.

**Comment by Elsonnnn** [comment]
okay looks good
