### ISSUE TITLE
2.6 M2 Specific Requirement

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#60]
On the M1 that has been affected and need to be removed. And included any update from M1 in.
With reference to M1 Deliverable Update, those who are assigned will have to add in to the M2 Report

**Comment by 2101035** [comment]
Added into M2 report, for example, our UIR that was lacking in M1 report.



![Image](https://user-images.githubusercontent.com/94104852/198569627-89e2ce45-27b7-4622-a149-122a4f8a3306.png)

**Comment by Elsonnnn** [comment]
okay nice
