### ISSUE TITLE
Email Replied from Client meeting

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#63]
Client replies on the email that we sent out on Week 6.
 
1) based on our estimations, the man hours are more than the 12 weeks we were allocated to work with you, may we propose to reduce scope such as just working on a web application to support the requirements instead of both the web and mobile services?
>> okay.
 
2) Regarding the layout of the web application, are there any features that the application must possess?
>> We have discussed this is great detail in the project description and client meeting.
 
3) Would the company logo be required on any of the pages of the web application? 
>> Yes, you can use a nice logo for this project.
 
4) May we also check with regards towards the maintenance of the application, what hours are acceptable to conduct scheduled maintenance?
>> It has to be up 24 hours, 7 days a week. So what do you suggest?

 
5) For the color tones for the website, we noticed that there are a few tones such as the NHS blues, NHS neutrals, NHS support greens and the NHS highlights, what might you prefer to be used in this application?
>> Purple (#592a9c) and White (#FDEDFD)

 
6) What font size and font type would be preferred for the web application?
>> 14pt

7) What kind of company logo do you want? Do you have a specific logo that you have designed? If you do not, what colour do you want for the logo?
>> You can use a nice logo for me in this project
 
8) Is the IT admin's only role to add or edit staff's details?
>> Yes
 
9) does the manager come up with the scheduling with regards to logistics?
>> Yes
 
10) does manager update the scheduling and resubmit the scheduling?
>> Yes
 
11) is the workload management not linked to any hospital patient records, and the only sensitive information are the staff's particulars and the role they can perform
>> No
 
12) does staff need to update their job preference specifically a week in advance as they would be able to add or edit their availability up to 5 weeks ahead of time
>> No
 
13) are any logistics shortages handled by manager?
>> Don't know what you are asking here.
 
14) does staff and manager information only consist of full name, email, password and role?
>> Training and qualifications for the job
 
15) can IT admin view all staff and managers' details?
>> No

**Comment by xllRyan** [comment]
the following will be updated under the specific requirement for M2 Report

**Comment by Elsonnnn** [comment]
ok

**Comment by 2101035** [comment]
Noted, thanks!
