### ISSUE TITLE
3.1.1  Black box testing 1

### ISSUE THREAD

**Issue by Elsonnnn** [2101035/ICT2201-Team-Project-p1-7#65]

**Comment by Sy989** [comment]
Draft 1: (first draft for decision table)
![image](https://user-images.githubusercontent.com/95022493/203708681-0d678d9e-a0ef-456d-8462-0c6127ec6c8e.png)

**Comment by Sy989** [comment]
Draft 2: (second draft for decision table)
![image](https://user-images.githubusercontent.com/95022493/203705988-41992e1b-12fb-467d-aa5a-d6584666e18f.png)

**Comment by Sy989** [comment]
Draft 3: (third draft for decision table)
![image](https://user-images.githubusercontent.com/95022493/203708515-bf51108d-a200-4df8-8c51-2692b6e2c23f.png)

**Comment by xllRyan** [comment]
looks good

**Comment by Sy989** [comment]
Draft(equivalence partitioning):
![image](https://user-images.githubusercontent.com/95022493/203727405-d421fc5f-2d57-4448-80bc-5f497a511e93.png)
Draft(action state):
![image](https://user-images.githubusercontent.com/95022493/203727576-70d10cab-b5de-414d-bc36-aee1349cb67f.png)

**Comment by 2101035** [comment]
I think these drafts look okay, we can use them for the final report

**Comment by Elsonnnn** [comment]
Okay nice
