### ISSUE TITLE
3.1.2 Black box testing 2

### ISSUE THREAD

**Issue by Elsonnnn** [2101035/ICT2201-Team-Project-p1-7#66]

**Comment by xllRyan** [comment]
![Image](https://user-images.githubusercontent.com/20891220/203727306-9cb40298-8f43-4755-bead-e50d66875a30.png)

These is the eEquivalence Partitioning for the black-box testing

**Comment by Elsonnnn** [comment]
![Image](https://user-images.githubusercontent.com/90232363/203805203-07836fb1-ad2d-4a65-890f-63048d8aa555.png)

Boundary testing for black-box testing

**Comment by 2101035** [comment]
Updated Equivalence partitioning and boundary value analysis

![Image](https://user-images.githubusercontent.com/94104852/204079485-873919db-901e-4d68-98b5-004c4445df8e.png)
