### ISSUE TITLE
3.2.1 white box testing 1

### ISSUE THREAD

**Issue by Elsonnnn** [2101035/ICT2201-Team-Project-p1-7#67]

**Comment by Elsonnnn** [comment]
Pseudocode
![Image](https://user-images.githubusercontent.com/90232363/203795663-6e811568-b984-4b75-8d31-089c5406e2fc.png)

CFG


![Image](https://user-images.githubusercontent.com/90232363/203795756-5c5b8012-954d-44ad-99a1-292b4af100a7.png)

**Comment by xllRyan** [comment]
good work for white box testing

**Comment by 2101035** [comment]
CFG looks clear, let's use this for our final report
