### ISSUE TITLE
3.2.2 white box testing 2

### ISSUE THREAD

**Issue by Elsonnnn** [2101035/ICT2201-Team-Project-p1-7#68]

**Comment by Elsonnnn** [comment]
Basis path
![Image](https://user-images.githubusercontent.com/90232363/203795869-af071b12-eebb-47db-8829-9dfe22358873.png)

Basis path test specifications and test cases


![Image](https://user-images.githubusercontent.com/90232363/203795985-d6a634fd-cdbd-4c55-ae5f-4a6d81bb9cd6.png)

**Comment by 2101035** [comment]
There are 6 basis paths, so we have 6 test cases to test these paths.

**Comment by Elsonnnn** [comment]
yes
