### ISSUE TITLE
2.1 Project estimation

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#7]
Project estimation
it's the process of analyzing available data to predict the time, cost, and resources needed to complete a project.

**Comment by Elsonnnn** [comment]
Done the project estimation for the M1 report

**Comment by Elsonnnn** [comment]
Screenshots

![Image](https://user-images.githubusercontent.com/90232363/191903588-4ff617b8-3340-4571-88cb-1a5b6fda6d73.png)

![Image](https://user-images.githubusercontent.com/90232363/191903718-6f93efc8-6db6-4d40-bb07-bb228624c698.png)

![Image](https://user-images.githubusercontent.com/90232363/191903766-9a0d336a-894f-4df1-be56-1a6c1b7fae7e.png)

![Image](https://user-images.githubusercontent.com/90232363/191903844-84fb4dd8-5213-4a9d-a4f4-b923a6c7a6c0.png)
