### ISSUE TITLE
3.3.2 Prototype 2

### ISSUE THREAD

**Issue by Elsonnnn** [2101035/ICT2201-Team-Project-p1-7#70]

**Comment by Sy989** [comment]
Created Logo for prototype:
![nhs_2](https://user-images.githubusercontent.com/95022493/204079166-284faee0-b270-4f11-a534-ab165fa423a8.png)

**Comment by Sy989** [comment]
Recorded the videos for Ryan to edit:
![image](https://user-images.githubusercontent.com/95022493/204079222-3edc089f-0715-46ad-b8a2-c5a5b165b741.png)

**Comment by Sy989** [comment]
Videos here:

[videos.zip](https://github.com/2101035/ICT2201-Team-Project-p1-7/files/10095897/videos.zip)

**Comment by Elsonnnn** [comment]
looks good

**Comment by 2101035** [comment]
I think the logo fits the criteria from the client. Nice!
