### ISSUE TITLE
3.4 Review Documents for Testing

### ISSUE THREAD

**Issue by Elsonnnn** [2101035/ICT2201-Team-Project-p1-7#71]

**Comment by 2101035** [comment]
Our test cases, please take a look and check if we are missing any details

[M3 Testing - BB Test cases-1.pdf](https://github.com/2101035/ICT2201-Team-Project-p1-7/files/10095907/M3.Testing.-.BB.Test.cases-1.pdf)

**Comment by Elsonnnn** [comment]
Ok nice

**Comment by Sy989** [comment]
looks good
