### ISSUE TITLE
Retrospection

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#72]
Do more of:
Focus the communication between team members over chat.
Clear communications and clarification of doubts.
Less of:
Side track during meeting causing the meeting to span over long period of time and effectiveness goes down,
We should reduce the timings of meetings, through gathering the topics to be discussed beforehand and not during the meeting.
Keep doing:
We should keep on having short daily meetings but structure it hierarchically.
Start doing:
A social interaction meeting with colleagues as it releases the stress, makes us happy and motivates team members.
Stop doing:
We should stop calling other team members unnecessarily, to allow them to focus on their taskings, calls/discussions should occur during meetings. Or to settle privately to the exact party that they need clarification with.

**Comment by xllRyan** [comment]
This is our retrospection for M2 Reviews

**Comment by 2101035** [comment]
yes, i agree

**Comment by Elsonnnn** [comment]
Yes lets work hard for M3
