### ISSUE TITLE
3.3.3 Prototype 3

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#73]

**Comment by 2101035** [comment]
Completed the calendar view for employee on figma

![Image](https://user-images.githubusercontent.com/94104852/204079268-a51bb968-a0fd-42e0-ab75-5a044ab02e51.png)

**Comment by Elsonnnn** [comment]
Looks good

**Comment by Sy989** [comment]
looks good for project requirements
