### ISSUE TITLE
3.3.4 Prototype 4

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#74]
![Image](https://user-images.githubusercontent.com/20891220/204068116-6ef64217-89b8-44cb-b7e8-fdc2fd3f6dc6.png)

Account management page - where the user can  update their password.

![Image](https://user-images.githubusercontent.com/20891220/204068133-a2e94486-111b-4040-bf86-1d33f8a9c5b3.png)

Login page

![Image](https://user-images.githubusercontent.com/20891220/204068139-fc6eba4e-3ca5-4b11-90e2-0a7b0c86bcad.png)

Change password page

**Comment by xllRyan** [comment]
what do you think of the prototype from the above?

**Comment by Elsonnnn** [comment]
I think it looks great
