### ISSUE TITLE
3.1.3 State transition table

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#76]
Emphasize state.
• 'Flow’ here is from one
state to another
• Describe a closed system
composed of discrete
states.
• Describe how a system
behaves to actions or
events.

**Comment by xllRyan** [comment]
All of us will come together to discuss the state transition table.

**Comment by Sy898** [comment]
Draft 1:
![State Transition diagram drawio](https://user-images.githubusercontent.com/101309971/203218382-5ab6b1ec-065a-4c4f-8e9e-653df21582d4.png)

**Comment by xllRyan** [comment]
![Image](https://user-images.githubusercontent.com/20891220/203727523-aff576fd-ee9e-4773-8f9e-4febf99df360.png)

updated one

**Comment by xllRyan** [comment]
![Image](https://user-images.githubusercontent.com/20891220/204067838-dc966335-fccc-450c-94a2-cd6d0a08f6bf.png)

updated version

**Comment by Sy989** [comment]
looks good

**Comment by 2101035** [comment]
i agree

**Comment by Elsonnnn** [comment]
yes I agree too
